### PR TITLE
Create Average of Levels in Binary Tree

### PR DESCRIPTION
**Pull request by pushpendrasahu11**
Added solution to leetcode problem 637- Average of Levels in Binary Tree.

### CODE REVIEW

**Comment by Keerat666** [comment]
Please create an issue for this.

https://github.com/Keerat666/LeetCode-HacktoberFest22/discussions/141

**Comment by pushpendrasahu11** [comment]
I have created issue #213 for this.

**Comment by Keerat666** [comment]
Please put your solution in the correct folder 

https://github.com/Keerat666/LeetCode-HacktoberFest22/discussions/141

**Comment by pushpendrasahu11** [comment]
added solution inside folder.

**Pull request closed without merging**
